### PR TITLE
Add index pages

### PR DESCRIPTION
**Pull request by parkr**
Both for HTML & Markdown.

Coming from Liquid, handlebars is a bit weird. Had to run but wanted to share what I have so far. Pretty simple.

Ref: #16.

### CODE REVIEW

**Comment by parkr** [comment]
Hey! :sparkles: 

I think I have come to a solution I'm OK with. It's by no means perfect and the design for the HTML page just steals the comments paradigm, but hey, it's something. Makes browsing the issues a little easier. Just needs a little design love. :lipstick: 

## HTML

screen shot 2015-04-23 at 10 58 46 am

## MD

screen shot 2015-04-23 at 10 58 35 am

Let me know what you think!

/cc @jlord @muan

**Comment by jlord** [comment]
@parkr I am so excited about this! I'll pull it down and try it out a little later today :sparkles:

**Comment by parkr** [comment]
> @parkr I am so excited about this! I'll pull it down and try it out a little later today

Yay! :tada: Can't wait to hear your thoughts. Definitely opportunity to clean up writemarkdown/writehtml in terms of the input data / template / output file pipeline but it might also confuse more than it helps. :)

**Comment by jlord** [comment]
Kewl, it looks good to me! @muan thoughts?

**Comment by krlmlr** [comment]
This doesn't work well when more than one repository is queried for. Might get auto-fixed if each repo is put into a single subdirectory (#4).

**Comment by parkr** [comment]
@krlmlr What fails?

**Comment by krlmlr** [comment]
I tried only once and found that links on the index page sometimes refer to wrong repositories/issues.

**Comment by parkr** [comment]
@krlmlr For which repos did you run this? I'd be interested in fixing that bug.

**Comment by krlmlr** [comment]
I don't remember. Does it work for you when you try downloading for two (random, unrelated) repos at once? Or for five repos?

**Comment by Muriuki-njeri** [comment]
qul staff for sure.

**Pull request closed without merging**
