### PR TITLE
Add instructions for local install

### PR DESCRIPTION
**Pull request by krlmlr**
I'm not sure if this is the best way, but it worked for me. Thanks for your feedback.

### CODE REVIEW

**Comment by jlord** [comment]
Have you run `npm link` from within your clone? That should give you access to `offline-issues` command using your local code.

**Comment by jlord** [comment]
PS—I'm super thankful for documentation PRs! I just wanted to check with you on that point because that step would fall under "Local Install" and likely replace the second step currently proposed :sparkles:

**Comment by krlmlr** [comment]
Thanks. I'm totally new to Node.js. I see that `npm link` requires root rights on my machine, I'm totally fine with running bleeding-edge versions from a local sandbox. I'll update the pull request to include both options.

**Comment by krlmlr** [comment]
Updated. I hope it's not too complicated (and still somehow correct) now.

**Comment by jlord** [comment]
:+1:

**Pull request merged**
